services:
  # A Docker web service
  - type: web
    name: alist
    env: docker
    repo: https://github.com/alist-org/alist-render.git # optional
    region: virginia
    plan: free # optional (defaults to starter)
    healthCheckPath: /
    envVars:
    - fromGroup: alist
